from django.urls import path

from . import views

urlpatterns = [path('csrf/', views.csrf_token_view, name='get-csrf'),
               path('', views.TransactionListView.as_view(), name='transaction_list'),
               path('add/', views.transaction_add, name='transaction_add'),
               path('delete/<int:pk>/', views.transaction_delete, name='transaction_delete'),
               path('update/<int:pk>/', views.TransactionUpdateView.as_view(), name='transaction_update'),
               path('import/', views.transaction_import, name='transaction_import'),
               path('export/', views.export_transactions, name='transaction_export'),
               path('budgets/', views.BudgetListView.as_view(), name='budget_list'),
               path('budgets/add/', views.BudgetCreateView.as_view(), name='budget_create'),
               path('goals/', views.FinancialGoalListView.as_view(), name='goal_list'),
               path('goals/add/', views.FinancialGoalCreateView.as_view(), name='goal_create'),
               path('goals/<int:pk>/add_savings', views.add_saving_to_goal, name='goal_add_savings'),
               path('debts/', views.DebtListView.as_view(), name='debt_list'),
               path('debts/add/', views.DebtCreateView.as_view(), name='debt_create'),
               path('debts/<int:pk>/pay/', views.pay_debt, name='pay_debt'),
               path('transfers/', views.TransferListView.as_view(), name='transfer_list'),
               path('transfers/add/', views.TransferCreateView.as_view(), name='transfer_create'),
               path('dashboard/', views.dashboard_view, name='dashboard'),
               path('wallets/', views.WalletListView.as_view(), name='wallet_list'),
               path('wallets/add/', views.WalletCreateView.as_view(), name='wallet_create'),
               path('wallets/update/<int:pk>/', views.WalletUpdateView.as_view(), name='wallet_update'),
               path('wallets/delete/<int:pk>/', views.WalletDeleteView.as_view(), name='wallet_delete'),
               path('categories/', views.CategoryListView.as_view(), name='category_list'),
               path('categories/add/', views.CategoryCreateView.as_view(), name='category_create'),
               path('categories/update/<int:pk>/', views.CategoryUpdateView.as_view(), name='category_update'),
               path('categories/delete/<int:pk>/', views.CategoryDeleteView.as_view(), name='category_delete'),
               path('payees/', views.PayeeListView.as_view(), name='payee_list'),
               path('payees/add/', views.PayeeCreateView.as_view(), name='payee_create'),
               path('payees/update/<int:pk>/', views.PayeeUpdateView.as_view(), name='payee_update'),
               path('payees/delete/<int:pk>/', views.PayeeDeleteView.as_view(), name='payee_delete'),
               path('<int:pk>/details/', views.TransactionDetailView.as_view(), name='transaction_detail'),
               path('item/delete/<int:pk>/', views.purchase_item_delete, name='purchase_item_delete'),
               path('item/update/<int:pk>/', views.purchase_item_update, name='purchase_item_update'),
               path('whoami/', views.whoami, name='whoami'),]
