version: '3.8'

services:
  backend:
    build: ./backend
    container_name: finance_tracker_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=finance_tracker_app.settings
      - DJANGO_SECRET_KEY=g#es0&d=vcuw)h@gobtlav)z4tg4d1jx!guec-=iimin9bn1+u

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: finance_tracker_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: npm run dev