"""
Django settings for finance_tracker_app project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# finance_tracker_app/settings.py

# ...
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# Hapus semua blok ALLOWED_HOSTS dan CSRF_TRUSTED_ORIGINS yang tersebar
# dan ganti dengan blok terpusat ini.
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SAMESITE = 'Lax'
ALLOWED_HOSTS = []
CSRF_TRUSTED_ORIGINS = []
CORS_ALLOWED_ORIGINS = []

if DEBUG:
    ALLOWED_HOSTS.extend(['localhost', '127.0.0.1'])
    CSRF_TRUSTED_ORIGINS.extend(['http://localhost:5173', 'http://127.0.0.1:5173'])
    CORS_ALLOWED_ORIGINS.extend(['http://localhost:5173', 'http://127.0.0.1:5173'])

# Ambil URL utama aplikasi dari environment variable DigitalOcean
# Contoh: https://nama-app-anda.ondigitalocean.app
APP_URL = os.environ.get('APP_URL')
if APP_URL:
    # CSRF_TRUSTED_ORIGINS butuh URL lengkap dengan https://
    CSRF_TRUSTED_ORIGINS.append(APP_URL)
    # CORS_ALLOWED_ORIGINS juga butuh URL lengkap
    CORS_ALLOWED_ORIGINS.append(APP_URL)
    # ALLOWED_HOSTS hanya butuh hostname-nya saja, tanpa https://
    # Kita ambil dari variabel APP_DOMAIN yang juga disediakan DigitalOcean
    APP_DOMAIN = os.environ.get('APP_DOMAIN')
    if APP_DOMAIN:
        ALLOWED_HOSTS.append(APP_DOMAIN)

# Izinkan custom domain jika ada
CUSTOM_DOMAIN = os.environ.get('CUSTOM_DOMAIN')  # misal: www.domainanda.com
if CUSTOM_DOMAIN:
    ALLOWED_HOSTS.append(CUSTOM_DOMAIN)
    CSRF_TRUSTED_ORIGINS.append(f"https://{CUSTOM_DOMAIN}")
    CORS_ALLOWED_ORIGINS.append(f"https://{CUSTOM_DOMAIN}")

CORS_ALLOW_CREDENTIALS = True

# Tambahkan origin untuk production dari environment variable
prod_origin = os.environ.get('CORS_PROD_ORIGIN')
if prod_origin:
    CORS_ALLOWED_ORIGINS.append(prod_origin)

# Application definition
INSTALLED_APPS = ['django.contrib.admin', 'django.contrib.auth', 'django.contrib.contenttypes',
                  'django.contrib.sessions', 'django.contrib.messages', 'django.contrib.staticfiles', 'rest_framework',
                  'rest_framework.authtoken', 'corsheaders', 'dj_rest_auth', 'dj_rest_auth.registration',
                  'transactions', ]

MIDDLEWARE = ['django.middleware.security.SecurityMiddleware', 'whitenoise.middleware.WhiteNoiseMiddleware',
              'django.contrib.sessions.middleware.SessionMiddleware', 'corsheaders.middleware.CorsMiddleware',
              'django.middleware.common.CommonMiddleware', 'django.middleware.csrf.CsrfViewMiddleware',
              'django.contrib.auth.middleware.AuthenticationMiddleware',
              'django.contrib.messages.middleware.MessageMiddleware',
              'django.middleware.clickjacking.XFrameOptionsMiddleware', ]

ROOT_URLCONF = 'finance_tracker_app.urls'

TEMPLATES = [
    {'BACKEND': 'django.template.backends.django.DjangoTemplates', 'DIRS': [BASE_DIR / 'templates'], 'APP_DIRS': True,
     'OPTIONS': {'context_processors': ['django.template.context_processors.request',
                                        'django.contrib.auth.context_processors.auth',
                                        'django.contrib.messages.context_processors.messages', ], }, }, ]

WSGI_APPLICATION = 'finance_tracker_app.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
if 'DATABASE_URL' in os.environ:
    DATABASES = {'default': dj_database_url.config(conn_max_age=600, ssl_require=True)}
else:
    DATABASES = {'default': {'ENGINE': 'django.db.backends.sqlite3', 'NAME': BASE_DIR / 'db.sqlite3', }}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [{'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator', },
                            {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', },
                            {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator', },
                            {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator', }, ]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Jakarta'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Tambahkan setting ini untuk production
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

LOGOUT_REDIRECT_URL = '/'
LOGIN_REDIRECT_URL = '/dashboard/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
