# Generated by Django 5.2.4 on 2025-07-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_financialgoal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lender_name', models.CharField(max_length=100)),
                ('initial_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
