# Generated by Django 5.2.4 on 2025-07-26 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_debt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('admin_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('transfer_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('from_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='transactions.wallet')),
                ('to_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='transactions.wallet')),
            ],
        ),
    ]
